# Generated by Django 4.2.4 on 2023-09-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0015_alter_weekcomment_parent_weekvisit_ccdetailvisit'),
        ('ks_course', '0008_coursevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_audio', '0005_audiovisit'),
        ('ks_vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevote',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='articlevote',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True),
        ),
        migrations.CreateModel(
            name='WeekVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.week')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CCDetailVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('ccdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.ccdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
