# Generated by Django 4.2.4 on 2023-10-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_vote', '0003_question_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='choice2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='choice3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='choice4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
