# Generated by Django 4.2.4 on 2023-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_vote', '0007_audioweekvote_audioweekplaylist_audioplaylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioplaylist',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioweekplaylist',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
