# Generated by Django 4.2.4 on 2023-12-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0028_rename_audio_article_audioarticlechapter_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_vote', '0008_audioplaylist_is_delete_audioweekplaylist_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArticleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audioarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
