# Generated by Django 4.2.4 on 2023-08-13 06:00

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0001_initial'),
        ('ks_audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utility.utils.upload_audio_file_path),
        ),
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path),
        ),
        migrations.AddField(
            model_name='audio',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path),
        ),
        migrations.CreateModel(
            name='AudioCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=utility.utils.upload_audio_course_file_path)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('section_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_course.sectioncourse')),
            ],
        ),
    ]
