# Generated by Django 4.2.4 on 2023-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0002_audio_file_audio_image_audio_thumb_audiocourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='audiocourse',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='audio',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiocourse',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiocourse',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
