# Generated by Django 4.2.4 on 2023-09-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0016_ccdetailvisit_create_date_weekvisit_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_audio', '0005_audiovisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=utility.utils.upload_audio_course_file_path)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_lock', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('section_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.sectionweek')),
            ],
        ),
        migrations.AddField(
            model_name='audiovisit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AudioWeekVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('audio_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audioweek')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioWeekChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('audio_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audioweek')),
            ],
        ),
        migrations.CreateModel(
            name='AudioCourseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('audio_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audiocourse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioCourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('audio_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audiocourse')),
            ],
        ),
        migrations.CreateModel(
            name='AudioChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audio')),
            ],
        ),
    ]
