# Generated by Django 4.2.4 on 2023-09-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0016_ccdetailvisit_create_date_weekvisit_create_date'),
        ('ks_course', '0008_coursevisit'),
        ('ks_audio', '0006_audioweek_audiovisit_create_date_audioweekvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='ccdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_category.ccdetail'),
        ),
        migrations.AddField(
            model_name='audiocourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_course.course'),
        ),
        migrations.AddField(
            model_name='audioweek',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_category.week'),
        ),
    ]
