# Generated by Django 4.2.4 on 2023-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0008_remove_audio_ccdetail_remove_audiocourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochapter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiochapter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiocoursechapter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiocoursechapter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioweekchapter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioweekchapter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
