# Generated by Django 4.2.4 on 2023-10-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0010_alter_audio_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'permissions': [('can_view_monetary_audios', 'Can view monetary audios')]},
        ),
    ]
