# Generated by Django 4.2.4 on 2023-10-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0011_alter_audio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'permissions': [('can_view_monetary_audio', 'Can view monetary audio')]},
        ),
        migrations.AlterModelOptions(
            name='audioweek',
            options={'permissions': [('can_view_monetary_audio_week', 'Can view monetary audio week')]},
        ),
    ]
