# Generated by Django 4.2.4 on 2023-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0012_alter_audio_options_alter_audioweek_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.IntegerField(choices=[(1, 'FREE'), (2, 'LOCKED'), (3, 'LOCKED_WITH_QUESTION'), (4, 'LOCKED_RELY_TO_QUESTION')], default=1),
            preserve_default=False,
        ),
    ]
