# Generated by Django 4.2.4 on 2023-10-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0013_audio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ks_audio.audio'),
        ),
    ]
