# Generated by Django 4.2.4 on 2023-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0014_audio_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
