# Generated by Django 4.2.4 on 2023-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0015_audio_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioweek',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ks_audio.audioweek'),
        ),
        migrations.AddField(
            model_name='audioweek',
            name='type',
            field=models.IntegerField(choices=[(1, 'FREE'), (2, 'LOCKED'), (3, 'LOCKED_WITH_QUESTION'), (4, 'LOCKED_RELY_TO_QUESTION')], default=1),
            preserve_default=False,
        ),
    ]
