# Generated by Django 4.2.4 on 2023-11-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0016_audioweek_parent_audioweek_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
