# Generated by Django 4.2.4 on 2023-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0019_audiocourse_duration_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocourse',
            name='duration_audio',
        ),
        migrations.AlterField(
            model_name='audiocourse',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
