# Generated by Django 4.2.4 on 2023-11-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0020_remove_audiocourse_duration_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioweek',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
