# Generated by Django 4.2.4 on 2023-12-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0024_alter_audio_fake_dislike_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiochapter',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='audiocoursechapter',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='audioweekchapter',
            name='end_time',
        ),
    ]
