# Generated by Django 4.2.4 on 2023-12-18 18:02

from django.db import migrations, models
import django.utils.timezone
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0025_remove_audiochapter_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_lock', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField(null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('fake_played_count', models.IntegerField(default=5)),
                ('fake_like_count', models.IntegerField(default=8)),
                ('fake_dislike_count', models.IntegerField(default=1)),
            ],
        ),
    ]
