# Generated by Django 4.2.4 on 2023-12-18 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0026_audioarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArticleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('audio_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audioarticle')),
            ],
        ),
    ]
