# Generated by Django 4.2.4 on 2023-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0028_rename_audio_article_audioarticlechapter_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioarticle',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'FREE'), (2, 'LOCKED'), (3, 'LOCKED_WITH_QUESTION'), (4, 'LOCKED_RELY_TO_QUESTION')], null=True),
        ),
    ]
