# Generated by Django 4.2.4 on 2023-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0029_audioarticle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='type',
            field=models.IntegerField(choices=[(1, 'FREE'), (2, 'LOCKED'), (3, 'LOCKED_WITH_QUESTION'), (4, 'LOCKED_RELY_TO_QUESTION')]),
        ),
    ]
