# Generated by Django 4.2.4 on 2024-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0030_alter_audioarticle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='audioarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='audiocourse',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audiocourse',
            name='image',
        ),
        migrations.RemoveField(
            model_name='audiocourse',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='audioweek',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audioweek',
            name='image',
        ),
        migrations.RemoveField(
            model_name='audioweek',
            name='thumb',
        ),
    ]
