# Generated by Django 4.2.4 on 2024-12-24 19:12

from django.db import migrations, models
import django_ckeditor_5.fields
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0004_tag'),
        ('ks_audio', '0031_remove_audio_file_remove_audio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path),
        ),
        migrations.AddField(
            model_name='audio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.AddField(
            model_name='audioarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.AddField(
            model_name='audiocourse',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.AddField(
            model_name='audioweek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_audio_image_path),
        ),
        migrations.AddField(
            model_name='audioweek',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
