# Generated by Django 4.2.4 on 2024-12-27 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0032_audio_image_audio_tags_audioarticle_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audio')),
            ],
            options={
                'permissions': [('can_view_monetary_video', 'Can view monetary video')],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audio')),
            ],
            options={
                'permissions': [('can_view_monetary_file', 'Can view monetary file')],
            },
        ),
    ]
