# Generated by Django 4.2.4 on 2025-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0033_videoattachment_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='fake_visit_count',
            field=models.IntegerField(default=13),
        ),
    ]
