# Generated by Django 4.2.4 on 2025-01-03 11:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0034_audio_fake_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='references',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='References'),
        ),
    ]
