# Generated by Django 4.2.4 on 2025-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0035_audio_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['order'], 'permissions': [('can_view_monetary_audio', 'Can view monetary audio')]},
        ),
        migrations.AddField(
            model_name='audio',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
