# Generated by Django 4.2.4 on 2025-01-03 12:48

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0036_alter_audio_options_audio_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
