# Generated by Django 4.2.4 on 2025-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0037_audio_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
