# Generated by Django 4.2.4 on 2025-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0038_alter_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
