# Generated by Django 4.2.4 on 2025-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0048_audio_demo_url_alter_audio_fake_like_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochapter',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_dislike_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_like_count',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_played_count',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_visit_count',
            field=models.IntegerField(default=12),
        ),
    ]
