# Generated by Django 4.2.4 on 2025-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0050_alter_audio_fake_like_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochapter',
            options={'ordering': ['start_time_seconds']},
        ),
        migrations.AddField(
            model_name='audiochapter',
            name='start_time_seconds',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_dislike_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_like_count',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_played_count',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_visit_count',
            field=models.IntegerField(default=12),
        ),
    ]
