# Generated by Django 4.2.4 on 2025-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0064_alter_audio_fake_dislike_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='fake_dislike_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_like_count',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_played_count',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fake_visit_count',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='audiocourse',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
