# Generated by Django 4.2.4 on 2023-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0002_course_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='sectioncourse',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='sectioncourse',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
