# Generated by Django 4.2.4 on 2023-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0003_rename_active_course_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
