# Generated by Django 4.2.4 on 2023-08-23 06:11

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0004_course_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=utility.utils.upload_course_image_path),
        ),
    ]
