# Generated by Django 4.2.4 on 2023-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0001_initial'),
        ('ks_course', '0006_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank='True', default='', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tagcourse'),
        ),
    ]
