# Generated by Django 4.2.4 on 2023-10-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0008_coursevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'get_latest_by': 'create_date', 'permissions': (('fully_view_course', 'Can fully view course'),)},
        ),
    ]
