# Generated by Django 4.2.4 on 2023-10-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0010_course_price_transactioncourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncourse',
            old_name='gift_day',
            new_name='gift_percent',
        ),
    ]
