# Generated by Django 4.2.4 on 2023-10-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0015_alter_payment_create_date_alter_payment_payment_date_and_more'),
        ('ks_course', '0011_rename_gift_day_transactioncourse_gift_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncourse',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.payment'),
        ),
    ]
