# Generated by Django 4.2.4 on 2023-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0015_course_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'پیشرفته')], default=1),
            preserve_default=False,
        ),
    ]
