# Generated by Django 4.2.4 on 2023-11-06 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0016_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
