# Generated by Django 4.2.4 on 2023-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0017_course_has_practice_course_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
