# Generated by Django 4.2.4 on 2023-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0018_course_alt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fake_dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fake_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fake_subscriber_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fake_visit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
