# Generated by Django 4.2.4 on 2023-11-30 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0022_rename_fake_subscriber_count_course_fake_students_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncourse',
            old_name='is_active',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='transactioncourse',
            name='try_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactioncourse',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'قبل از پرداخت'), (2, 'خطا - قبل از پرداخت'), (3, 'پرداخت موفق')], default=1, null=True),
        ),
    ]
