# Generated by Django 4.2.4 on 2024-03-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0024_giftcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fake_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='off_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
