# Generated by Django 4.2.4 on 2024-03-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0025_course_fake_price_course_off_course_off_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncourse',
            name='gift_percent',
        ),
    ]
