# Generated by Django 4.2.4 on 2025-01-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0027_alter_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
