"""
Django settings for kheylisadas project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

import locale

# locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z!-jmcm9sulyq6vjd_7648vc9+kq0((%jsikvfia1t(!^+efv!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # external apps
    'django.contrib.humanize',
    'django_render_partial',
    'jalali_date',
    'sorl.thumbnail',
    'guardian',
    'captcha',
    # docs on https://django-ckeditor.readthedocs.io/en/latest/
    'ckeditor',  # CKEditor config
    'ckeditor_uploader',  # CKEditor media uploader

    # internal apps
    'ks_account',
    'ks_category',
    'ks_audio',
    'ks_course',
    'ks_article',
    'polls',
    'ks_tag',
    'ks_vote',
    'ks_user_panel',
    'ks_subscription',
    'ks_site',

    # for webpack
    'core',
    # for hls m3u8 files
    # 'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # for hls m3u8 files
    # 'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.common.CommonMiddleware',
]
# for hls m3u8 files
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:8000",
#     "http://localhost:8000",
#     "https://s3.ir-thr-at1.arvanstorage.com",
# ]

# ----------------------- security ---------
# settings.py
# توضیحات:
# SECURE_SSL_REDIRECT: تمامی درخواست‌ها به HTTPS هدایت می‌شوند.
# SECURE_HSTS: HSTS (HTTP Strict Transport Security) را فعال می‌کند.
# X_FRAME_OPTIONS: جلوگیری از Clickjacking.
# CSRF_COOKIE_SECURE و SESSION_COOKIE_SECURE: استفاده از کوکی‌های امن.
# CSRF_COOKIE_HTTPONLY: دسترسی به کوکی CSRF فقط از طریق HTTP.
# CORS: تنظیمات امنیتی برای دسترسی منابع از دامنه‌های خارجی.
# امنیت
# تنظیمات امنیتی برای محیط تولید
# settings.py

# امنیت (مناسب برای تولید، اما کامنت شده برای توسعه)
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True

# تنظیمات CSRF برای محیط توسعه
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False

# سایر تنظیمات امنیتی پیشنهادی (مناسب برای تولید، اما کامنت شده برای توسعه)
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

#  ======================= end security===========================

ROOT_URLCONF = 'kheylisadas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',
                 # Path(BASE_DIR, 'ks_account', 'templates')
                 ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kheylisadas.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

AUTH_USER_MODEL = 'ks_account.User'
LOGIN_URL = '/login/'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database', 'db.sqlite3'),
        # 'NAME': BASE_DIR / 'database/db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/statics/'  # show on front side

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets")  # show on real project
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

MEDIA_URL = '/medias/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media_root")
# MEDIA_ROOT = BASE_DIR / ''

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default settings (optional)
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}

# -------------------- for guardian config -----------
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # this is default
    'guardian.backends.ObjectPermissionBackend',
)
# -------------- capctcha config ----------
CAPTCHA_IMAGE_SIZE = (150, 50)
CAPTCHA_FONT_SIZE = 37
CAPTCHA_FOREGROUND_COLOR = '#112599'
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_MATH_CHALLENGE_OPERATOR = '+'
CAPTCHA_LETTER_ROTATION = None

# -------------- ckeditor Config ----------------
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
# CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
# CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'
# CKEDITOR_BASEPATH = STATIC_URL + "ckeditor/ckeditor/"
# CKEDITOR_BASEPATH = "/statics/ckeditor/ckeditor/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_SETTINGS = {
    'font_names': 'IRANSans'
}


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
# CKEDITOR_CONFIGS = {
#     'default':
#         {
#             'toolbar': {
#                                 'items': [
#                                     'heading',
#                                     '|',
#                                     'bold',
#                                     'italic',
#                                     'link',
#                                     '|',
#                                     'fontSize',
#                                     'fontColor',
#                                     '|',
#                                     'imageUpload',
#                                     'blockQuote',
#                                     'insertTable',
#                                     'undo',
#                                     'redo',
#                                     'codeBlock'
#                                 ]
#                             },
#                             'language': 'fa',
#                             'table': {
#                                 'contentToolbar': [
#                                     'tableColumn',
#                                     'tableRow',
#                                     'mergeTableCells'
#                                 ]
#                             },
#                             'licenseKey': '',
#                             'simpleUpload': {
#                                 # The URL that the images are uploaded to.
#                                 'uploadUrl': '/Uploader/UploadImage'
#                             }
#         },
# }
