# Generated by Django 4.2.4 on 2023-10-26 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_article', '0006_articlecategory_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
