# Generated by Django 4.2.4 on 2023-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_article', '0009_article_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
