# Generated by Django 4.2.4 on 2023-12-17 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_article', '0010_article_alt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
