# Generated by Django 4.2.4 on 2023-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_audio', '0026_audioarticle'),
        ('ks_course', '0023_rename_is_active_transactioncourse_is_paid_and_more'),
        ('ks_article', '0012_alter_article_description_rich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='article',
            name='audios',
            field=models.ManyToManyField(blank=True, to='ks_audio.audioarticle'),
        ),
        migrations.AddField(
            model_name='article',
            name='courses',
            field=models.ManyToManyField(blank=True, to='ks_course.course'),
        ),
    ]
