# Generated by Django 4.2.4 on 2023-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0003_tagweek'),
        ('ks_article', '0013_remove_article_icon_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tagarticle'),
        ),
    ]
