# Generated by Django 4.2.4 on 2023-12-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_article', '0014_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fake_dislike_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='fake_like_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='fake_visit_count',
            field=models.IntegerField(default=5),
        ),
    ]
