# Generated by Django 4.2.4 on 2024-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_article', '0015_article_fake_dislike_count_article_fake_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='thumb',
        ),
    ]
