# Generated by Django 4.2.4 on 2024-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0004_tag'),
        ('ks_article', '0017_alter_article_description_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
    ]
