# Generated by Django 4.2.4 on 2023-08-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
