# Generated by Django 4.2.4 on 2023-08-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0002_user_presenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_active_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
