# Generated by Django 4.2.4 on 2023-08-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0003_alter_user_mobile_active_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
