# Generated by Django 4.2.4 on 2023-08-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
