# Generated by Django 4.2.4 on 2023-10-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
