# Generated by Django 4.2.4 on 2023-10-16 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'LOGIN_SUCCESS'), (2, 'LOGIN_FAILED_INCORRECT_CAPTCHA'), (3, 'LOGIN_FAILED_INCORRECT_PASSWORD'), (4, 'SENT_REGISTER_SMS'), (5, 'SENT_RESET_PASSWORD_SMS')])),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
