# Generated by Django 4.2.4 on 2023-10-16 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.IntegerField(choices=[(1, 'LOGIN_SUCCESS'), (2, 'LOGIN_FAILED_INCORRECT_CAPTCHA'), (3, 'LOGIN_FAILED_INCORRECT_PASSWORD'), (4, 'SENT_ACTIVATION_SMS'), (5, 'SENT_RESET_PASSWORD_SMS')]),
        ),
    ]
