# Generated by Django 4.2.4 on 2023-10-16 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0011_alter_activitylog_create_date_alter_activitylog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 13, 59, 8, 33355, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
