# Generated by Django 4.2.4 on 2023-10-17 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0012_alter_activitylog_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
