# Generated by Django 4.2.4 on 2025-02-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_account', '0015_alter_activitylog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.IntegerField(choices=[(1, 'ورود موفق'), (2, 'ورود ناموفق - تصویر امنیتی اشتباه'), (3, 'ورود ناموفق - کلمه عبور اشتباه'), (4, 'ارسال پیامک فعالسازی'), (5, 'ارسال پیامک بازیابی رمز عبور'), (6, 'ثبت نام موفق'), (7, 'شماره موبایل نامعتبر'), (8, 'شماره موبایل تکراری'), (9, 'ارسال پیامک فعالسازی ناموفق'), (10, 'کد فعالسازی نامعتبر'), (11, 'کد فعالسازی منقضی شده'), (12, 'کاربر یافت نشد'), (13, 'خطای ثبت نام ناشناخته'), (14, 'خطای فعالسازی ناشناخته'), (15, 'کد فعالسازی وارد شده'), (16, 'کد فعالسازی اشتباه وارد شده'), (17, 'ورود ناموفق. کاربر یافت نشد.')]),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
