# Generated by Django 4.2.4 on 2023-10-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('eita', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('copy_right', models.TextField()),
                ('about_us_text', models.TextField()),
                ('site_logo1', models.ImageField(upload_to=utility.utils.upload_site_files_path)),
                ('site_logo2', models.ImageField(upload_to=utility.utils.upload_site_files_path)),
                ('site_logo3', models.ImageField(upload_to=utility.utils.upload_site_files_path)),
                ('is_main_setting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
