# Generated by Django 4.2.4 on 2023-10-30 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
