# Generated by Django 4.2.4 on 2023-10-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0003_frequentquestioncategory_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentquestion',
            old_name='description',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_site.frequentquestioncategory'),
        ),
    ]
