# Generated by Django 4.2.4 on 2023-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0004_rename_description_frequentquestion_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('name', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
