# Generated by Django 4.2.4 on 2023-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0005_agecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='eita',
            new_name='eitaa',
        ),
    ]
