# Generated by Django 4.2.4 on 2023-11-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0006_rename_eita_sitesetting_eitaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
