# Generated by Django 4.2.4 on 2023-11-14 17:25

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0007_sitesetting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='avatar_admin',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='avatar_staff',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path),
        ),
    ]
