# Generated by Django 4.2.4 on 2023-11-18 17:38

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0008_sitesetting_avatar_sitesetting_avatar_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path)),
                ('avatar_admin', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path)),
                ('avatar_staff', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_avatar_image_path)),
                ('is_main', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='avatar_admin',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='avatar_staff',
        ),
    ]
