# Generated by Django 4.2.4 on 2023-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0010_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
