# Generated by Django 4.2.4 on 2023-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0012_accountsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='title_ks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
