# Generated by Django 4.2.4 on 2023-12-15 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0013_accountsetting_title_ks'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='login_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
