# Generated by Django 4.2.4 on 2023-12-15 22:42

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0014_accountsetting_login_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_site_files_path),
        ),
    ]
