# Generated by Django 4.2.4 on 2024-02-12 12:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0015_sitesetting_site_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='plan_description_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
