# Generated by Django 4.2.4 on 2024-12-23 20:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0016_sitesetting_about_us_rich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='plan_description_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
