# Generated by Django 4.2.4 on 2025-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0017_alter_sitesetting_about_us_rich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='articles_is_disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='courses_is_disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='weeks_is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
