# Generated by Django 4.2.4 on 2025-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0018_sitesetting_articles_is_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='page_message',
            field=models.TextField(default=''),
        ),
    ]
