# Generated by Django 4.2.4 on 2025-01-03 12:18

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0019_sitesetting_page_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_us_text',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='about_us'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='plan_description_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='plan_description'),
        ),
    ]
