# Generated by Django 4.2.4 on 2025-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0020_remove_sitesetting_about_us_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
