# Generated by Django 4.2.4 on 2025-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0021_sitesetting_maintenance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
