# Generated by Django 4.2.4 on 2025-01-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0022_alter_contactus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='full_name',
        ),
    ]
