# Generated by Django 4.2.4 on 2023-08-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagarticle',
            name='slug',
            field=models.SlugField(blank='True', default='', null=True),
        ),
        migrations.AlterField(
            model_name='tagccdetail',
            name='slug',
            field=models.SlugField(blank='True', default='', null=True),
        ),
        migrations.AlterField(
            model_name='tagcourse',
            name='slug',
            field=models.SlugField(blank='True', default='', null=True),
        ),
    ]
