# Generated by Django 4.2.4 on 2024-12-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0027_alter_course_tags'),
        ('ks_article', '0018_alter_article_tags'),
        ('ks_tag', '0004_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagArticle',
        ),
        migrations.DeleteModel(
            name='TagCCDetail',
        ),
        migrations.DeleteModel(
            name='TagCourse',
        ),
        migrations.DeleteModel(
            name='TagWeek',
        ),
    ]
