# Generated by Django 4.2.4 on 2023-08-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='ks_category.chapter'),
        ),
        migrations.CreateModel(
            name='CCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=150)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.category')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.chapter')),
            ],
            options={
                'verbose_name': 'فصل دسته',
                'verbose_name_plural': 'فصل دسته ها',
            },
        ),
    ]
