# Generated by Django 4.2.4 on 2023-08-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0002_category_chapters_ccdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccdetail',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ccdetail',
            old_name='chapter_id',
            new_name='chapter',
        ),
    ]
