# Generated by Django 4.2.4 on 2023-08-09 03:20

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0003_rename_category_id_ccdetail_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ccdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_category_image_path),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='icon',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_category_image_path),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_category_image_path),
        ),
        migrations.AddField(
            model_name='chapter',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_category_image_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='ccdetail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ccdetail',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='icon',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
