# Generated by Django 4.2.4 on 2023-08-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0004_alter_category_options_alter_ccdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
