# Generated by Django 4.2.4 on 2023-08-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0005_ccdetail_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('ccdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.ccdetail')),
            ],
        ),
    ]
