# Generated by Django 4.2.4 on 2023-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0007_alter_ccdetail_name_alter_ccdetail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='ccdetail',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
