# Generated by Django 4.2.4 on 2023-08-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0009_ccdetailcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='slug',
            field=models.SlugField(blank='True', default='', null=True),
        ),
    ]
