# Generated by Django 4.2.4 on 2023-08-27 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_tag', '0002_alter_tagarticle_slug_alter_tagccdetail_slug_and_more'),
        ('ks_category', '0011_ccdetail_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('icon', models.CharField(default='A', max_length=10)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_week_image_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_week_image_path)),
                ('slug', models.SlugField(blank='True', default='', null=True)),
                ('description', models.TextField(null=True)),
                ('tags', models.ManyToManyField(blank=True, to='ks_tag.tagccdetail')),
            ],
        ),
        migrations.CreateModel(
            name='WeekComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_category.ccdetailcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.week')),
            ],
        ),
    ]
