# Generated by Django 4.2.4 on 2023-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_tag', '0003_tagweek'),
        ('ks_category', '0012_week_weekcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tagweek'),
        ),
    ]
