# Generated by Django 4.2.4 on 2023-08-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0013_alter_week_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.week')),
            ],
        ),
    ]
