# Generated by Django 4.2.4 on 2023-09-15 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0015_alter_weekcomment_parent_weekvisit_ccdetailvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetailvisit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekvisit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
