# Generated by Django 4.2.4 on 2023-10-17 19:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0016_ccdetailvisit_create_date_weekvisit_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 80012), editable=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 78013), editable=False),
        ),
        migrations.AddField(
            model_name='section',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 81012), editable=False),
        ),
        migrations.AddField(
            model_name='sectionweek',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 85992), editable=False),
        ),
        migrations.AddField(
            model_name='week',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 81996), editable=False),
        ),
        migrations.AlterField(
            model_name='ccdetailcomment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 84009), editable=False),
        ),
        migrations.AlterField(
            model_name='ccdetailvisit',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 86991), editable=False),
        ),
        migrations.AlterField(
            model_name='weekcomment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 84009), editable=False),
        ),
        migrations.AlterField(
            model_name='weekvisit',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 48, 24, 87990), editable=False),
        ),
    ]
