# Generated by Django 4.2.4 on 2023-11-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_site', '0005_agecategory'),
        ('ks_category', '0019_alter_ccdetailcomment_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_site.agecategory'),
        ),
        migrations.AddField(
            model_name='week',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_site.agecategory'),
        ),
    ]
