# Generated by Django 4.2.4 on 2023-11-06 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0021_ccdetail_level_week_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='has_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='week',
            name='has_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
