# Generated by Django 4.2.4 on 2023-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0022_ccdetail_has_practice_ccdetail_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='audio_url',
            field=models.URLField(null=True),
        ),
    ]
