# Generated by Django 4.2.4 on 2023-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0023_ccdetail_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_thumb_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
