# Generated by Django 4.2.4 on 2023-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0024_category_alt_image_category_alt_thumb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='alt_thumb_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
