# Generated by Django 4.2.4 on 2023-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0025_week_alt_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetail',
            name='fake_dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='fake_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccdetail',
            name='fake_visit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='fake_dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='fake_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='fake_visit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
