# Generated by Django 4.2.4 on 2023-11-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0026_ccdetail_fake_dislike_count_ccdetail_fake_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdetail',
            name='fake_dislike_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetail',
            name='fake_like_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetail',
            name='fake_visit_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='fake_dislike_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='fake_like_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='fake_visit_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
