# Generated by Django 4.2.4 on 2023-12-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0028_alter_ccdetail_fake_dislike_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='age_range',
            field=models.CharField(default='2 تا 3 ماهگی', max_length=30),
        ),
    ]
