# Generated by Django 4.2.4 on 2024-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0029_remove_category_icon_category_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccdetail',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='thumb',
        ),
        migrations.AddField(
            model_name='chapter',
            name='alt_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
