# Generated by Django 4.2.4 on 2024-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0030_remove_ccdetail_thumb_remove_chapter_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='audio_url',
            field=models.URLField(null=True),
        ),
    ]
