# Generated by Django 4.2.4 on 2024-12-24 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_tag', '0004_tag'),
        ('ks_audio', '0032_audio_image_audio_tags_audioarticle_tags_and_more'),
        ('ks_category', '0031_week_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.AlterField(
            model_name='week',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ks_tag.tag'),
        ),
        migrations.CreateModel(
            name='AudioWeekComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('audioweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audioweek')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_category.audioweekcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_audio.audio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_category.audiocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
