# Generated by Django 4.2.4 on 2025-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0032_alter_ccdetail_tags_alter_week_tags_audioweekcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
