# Generated by Django 4.2.4 on 2023-09-02 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank='True', default='', null=True)),
                ('icon', models.CharField(default='A', max_length=10)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
