# Generated by Django 4.2.4 on 2023-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0002_plan_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gift_day',
            field=models.IntegerField(default=0),
        ),
    ]
