# Generated by Django 4.2.4 on 2023-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0003_payment_is_paid_payment_price_payment_ref_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
