# Generated by Django 4.2.4 on 2023-09-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0009_rename_date_payment_create_date_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
