# Generated by Django 4.2.4 on 2023-09-05 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0010_alter_payment_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
