# Generated by Django 4.2.4 on 2023-09-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0012_alter_transaction_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_gift',
            field=models.IntegerField(default=0),
        ),
    ]
