# Generated by Django 4.2.4 on 2023-10-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0015_alter_payment_create_date_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Subscription'), (2, 'Course')], null=True),
        ),
    ]
