# Generated by Django 4.2.4 on 2023-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0020_transaction_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.IntegerField(blank=True, choices=[(1, 'نقدی'), (2, 'آنلاین')], default=2, null=True),
        ),
    ]
