# Generated by Django 4.2.4 on 2023-11-30 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0021_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='try_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'اشتراک'), (2, 'دوره')], null=True),
        ),
    ]
