# Generated by Django 4.2.4 on 2023-11-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0022_transaction_try_date_alter_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_active',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'قبل از پرداخت'), (2, 'خطا - قبل از پرداخت'), (3, 'پرداخت موفق')], default=1, null=True),
        ),
    ]
