# Generated by Django 4.2.4 on 2024-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_course', '0023_rename_is_active_transactioncourse_is_paid_and_more'),
        ('ks_subscription', '0025_plan_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='courses',
            field=models.ManyToManyField(blank=True, to='ks_course.course'),
        ),
    ]
