# Generated by Django 4.2.4 on 2024-02-28 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0026_alter_plan_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter the gift code', max_length=10, unique=True)),
                ('percentage', models.PositiveSmallIntegerField(help_text='Enter the discount percentage (e.g., 10 for 10%)')),
                ('max', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter the start date of the discount code', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter the end date of the discount code', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.plan')),
            ],
        ),
    ]
