# Generated by Django 4.2.4 on 2024-02-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0028_plan_off_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fake_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.IntegerField(blank=True, choices=[(1, 'نقدی'), (2, 'آنلاین'), (3, 'هدیه')], default=2, null=True),
        ),
    ]
