# Generated by Django 4.2.4 on 2024-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0029_plan_fake_price_plan_off_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('در حال پرداخت', 'در حال پرداخت'), ('پرداخت شده', 'پرداخت شده')], max_length=100, null=True),
        ),
    ]
