# Generated by Django 4.2.4 on 2024-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0030_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('در حال پرداخت', 'در حال پرداخت'), ('پرداخت شده', 'پرداخت شده'), ('خطا در پرداخت', 'خطا در پرداخت')], max_length=100, null=True),
        ),
    ]
