# Generated by Django 4.2.4 on 2024-12-23 20:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0031_payment_error_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
