# Generated by Django 4.2.4 on 2025-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0032_alter_plan_description_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
