# Generated by Django 4.2.4 on 2025-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0033_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('در حال پرداخت', 'در حال پرداخت'), ('پرداخت شده', 'پرداخت شده'), ('خطا در پرداخت', 'خطا در پرداخت'), ('تراکنش تکراری', 'تراکنش تکراری'), ('خطا از زرین پال', 'خطا از زرین پال'), ('خطا در درخواست', 'خطا در درخواست'), ('Timeout', 'Timeout'), ('خطا در اتصال', 'خطا در اتصال'), ('خطای نامشخص', 'خطای نامشخص'), ('خطا در قفل گذاری', 'خطا در قفل گذاری'), ('خطای پایگاه داده', 'خطای پایگاه داده'), ('لغو توسط کاربر', 'لغو توسط کاربر'), ('مبلغ نامعتبر', 'مبلغ نامعتبر'), ('اشتراک فعال', 'اشتراک فعال'), ('تراکنش در حال انجام', 'تراکنش در حال انجام')], max_length=100, null=True),
        ),
    ]
