# Generated by Django 4.2.4 on 2025-03-14 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_category', '0049_alter_ccdetail_fake_dislike_count_and_more'),
        ('ks_course', '0028_remove_course_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_subscription', '0034_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('fake_price', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('off_price', models.IntegerField(blank=True, null=True)),
                ('off', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank='True', default='', null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path)),
                ('campaign_gift', models.IntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, to='ks_course.course')),
            ],
            options={
                'permissions': (('fully_view_campaign', 'Can fully view campaign'),),
                'get_latest_by': 'create_date',
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='icon',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'اشتراک'), (2, 'دوره'), (2, 'کمپین')], null=True),
        ),
        migrations.CreateModel(
            name='CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('try_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('in_process', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'قبل از پرداخت'), (2, 'خطا - قبل از پرداخت'), (3, 'پرداخت موفق')], default=1, null=True)),
                ('gift_day', models.IntegerField(default=0)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.campaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.category')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(null=True)),
                ('description_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.campaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_category.category')),
            ],
        ),
    ]
