# Generated by Django 4.2.4 on 2025-03-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0035_campaign_remove_plan_icon_alter_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.plan'),
        ),
    ]
