# Generated by Django 4.2.4 on 2025-03-17 10:47

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0036_alter_transaction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner_chart',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner_course',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner_podcast',
            field=models.ImageField(blank=True, null=True, upload_to=utility.utils.upload_plans_image_path),
        ),
    ]
