# Generated by Django 4.2.4 on 2025-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0037_campaign_banner_3_campaign_banner_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_chart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_podcast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
