# Generated by Django 4.2.4 on 2025-03-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ks_subscription', '0038_campaign_description_3_campaign_description_chart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank='True', default='', null=True)),
                ('url', models.CharField(blank=True, max_length=2083, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CampaignQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=800)),
                ('message', models.TextField(max_length=5000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('campaign_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.campaignweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
