# Generated by Django 4.2.4 on 2025-03-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0039_campaignweek_campaign_is_open_campaignquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignweek',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.campaign'),
        ),
    ]
