# Generated by Django 4.2.4 on 2025-03-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0040_campaignweek_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignweek',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks_subscription.campaign'),
        ),
    ]
