# Generated by Django 4.2.4 on 2025-03-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0041_alter_campaignweek_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='is_recommended',
            new_name='is_published',
        ),
    ]
