# Generated by Django 4.2.4 on 2025-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0042_rename_is_recommended_campaign_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
