# Generated by Django 4.2.4 on 2025-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0043_chart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'اشتراک'), (2, 'دوره'), (3, 'کمپین')], null=True),
        ),
    ]
