# Generated by Django 4.2.4 on 2025-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0044_alter_chart_url_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
