# Generated by Django 4.2.4 on 2025-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0045_alter_chart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignquestion',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
