# Generated by Django 4.2.4 on 2025-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_subscription', '0046_campaignquestion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignquestion',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
